twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

jwt:
  secret: ${JWT_SECRET}

adapter:
  micro-users:
    url: ${USERS_SERVICE_URL}

feign:
  client:
    config:
      micro-users:
        connectTimeout: 5000
        readTimeout: 5000
